"use client";
import { useEffect, useMemo, useRef, useState } from "react";

type S="seven"|"bar"|"bell"|"diamond"|"cherry"|"lemon";
const DATA:Record<S,{g:string;p:number;src:string}>={seven:{g:"7",p:30,src:"/symbols/seven.png"},bar:{g:"BAR",p:18,src:"/symbols/bar.png"},diamond:{g:"Diamond",p:14,src:"/symbols/diamond.png"},bell:{g:"Bell",p:10,src:"/symbols/bell.png"},cherry:{g:"Cherry",p:7,src:"/symbols/cherry.png"},lemon:{g:"Lemon",p:5,src:"/symbols/lemon.png"}};
const KEYS=Object.keys(DATA) as S[];
const START:S[][]=[["seven","cherry","diamond"],["bar","lemon","bell"],["cherry","seven","bar"],["bell","diamond","lemon"],["seven","bar","seven"]];
const LINES:number[][]=[[0,0,0,0,0],[1,1,1,1,1],[2,2,2,2,2],[0,1,2,1,0],[2,1,0,1,2],[0,0,1,2,2],[2,2,1,0,0],[1,0,0,0,1],[1,2,2,2,1],[0,1,1,1,0],[2,1,1,1,2],[0,1,0,1,0],[2,1,2,1,2],[1,0,1,0,1],[1,2,1,2,1],[0,2,0,2,0],[2,0,2,0,2],[0,2,2,2,0],[2,0,0,0,2],[1,0,2,0,1]];
const COLORS=["#ffe66d","#59f3ff","#ff5aaa","#7cff77","#ff9f43"];
const SPIN_STRIPS:S[][]=Array.from({length:5},(_,reel)=>Array.from({length:12},(_,i)=>KEYS[(i*5+reel*2)%KEYS.length]));
const randomGrid=():S[][]=>Array.from({length:5},()=>Array.from({length:3},()=>KEYS[Math.floor(Math.random()*KEYS.length)]));

export default function Home(){
 const [grid,setGrid]=useState(START),[spinTarget,setSpinTarget]=useState(START),[coins,setCoins]=useState(1000),[bet,setBet]=useState(10),[count,setCount]=useState<10|20>(20),[spinning,setSpinning]=useState(false),[wins,setWins]=useState<number[]>([]),[amount,setAmount]=useState(0),[paytable,setPaytable]=useState(false),[sound,setSound]=useState(true),[auto,setAuto]=useState(false);
 const audioRef=useRef<AudioContext|null>(null),musicTimer=useRef<number|null>(null),musicStep=useRef(0),soundRef=useRef(true);
 useEffect(()=>{const n=Number(localStorage.getItem("lucky777-coins"));if(n>0)setCoins(n)},[]);
 useEffect(()=>localStorage.setItem("lucky777-coins",String(coins)),[coins]);
 const points=useMemo(()=>LINES.map(l=>l.map((r,c)=>`${50+c*100},${50+r*100}`).join(" ")),[]);
 function getAudio(){if(audioRef.current)return audioRef.current;const W=window as typeof window&{webkitAudioContext?:typeof AudioContext};const C=window.AudioContext||W.webkitAudioContext;if(!C)return null;audioRef.current=new C();return audioRef.current}
 function tone(freq:number,duration=.08,delay=0,volume=.07,type:OscillatorType="triangle"){if(!soundRef.current)return;const ctx=getAudio();if(!ctx)return;if(ctx.state==="suspended")ctx.resume();const o=ctx.createOscillator(),gain=ctx.createGain();o.type=type;o.frequency.value=freq;gain.gain.setValueAtTime(volume,ctx.currentTime+delay);gain.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+delay+duration);o.connect(gain);gain.connect(ctx.destination);o.start(ctx.currentTime+delay);o.stop(ctx.currentTime+delay+duration)}
 function startMusic(){if(musicTimer.current!==null)return;const melody=[262,330,392,523,392,330,294,349,440,587,440,349];musicStep.current=0;const tick=()=>{const i=musicStep.current++%melody.length;tone(melody[i],.22,0,.018,"sine");if(i%4===0)tone(melody[i]/2,.3,0,.012,"triangle")};tick();musicTimer.current=window.setInterval(tick,280)}
 function stopMusic(){if(musicTimer.current!==null){clearInterval(musicTimer.current);musicTimer.current=null}}
 function toggleSound(){const next=!soundRef.current;soundRef.current=next;setSound(next);if(next)startMusic();else stopMusic()}
 useEffect(()=>()=>{stopMusic();audioRef.current?.close()},[]);
 function score(g:S[][]){let total=0;const hit:number[]=[];LINES.slice(0,count).forEach((l,i)=>{const s=g[0][l[0]];let n=1;for(let c=1;c<5&&g[c][l[c]]===s;c++)n++;if(n>=3){hit.push(i);total+=DATA[s].p*(n-2)*Math.max(1,bet/10)}});return{total:Math.round(total),hit}}
 function spin(){if(spinning||coins<bet)return;if(soundRef.current)startMusic();const g=randomGrid(),r=score(g);tone(240,.09);setSpinTarget(g);setSpinning(true);setWins([]);setAmount(0);setCoins(v=>v-bet);window.setTimeout(()=>{setGrid(g);setWins(r.hit);setAmount(r.total);setCoins(v=>v+r.total);setSpinning(false);[0,1,2,3,4].forEach(i=>tone(360+i*55,.06,i*.07));if(r.hit.length)[0,1,2].forEach(i=>tone(680+i*140,.18,.42+i*.12))},1300)}
 useEffect(()=>{if(!auto||spinning)return;if(coins<bet){setAuto(false);return}const t=setTimeout(spin,wins.length?1200:450);return()=>clearTimeout(t)},[auto,spinning,coins]);
 const fullscreen=()=>document.fullscreenElement?document.exitFullscreen?.():document.documentElement.requestFullscreen?.();
 return <main className="game"><div className="stars"/><header><div className="counter"><small>COINS</small><b>{coins}</b></div><h1>LUCKY <em>777</em></h1><div className="right"><div className="counter"><small>BET</small><b>{bet}</b></div><button className="sound" onClick={toggleSound} aria-label={sound?"Mute music and effects":"Enable music and effects"}>{sound?"🔊":"🔇"}</button></div></header>
 <section className={`machine ${wins.length?"winGlow":""}`}><div className="bulbs"/><div className="jackpot">♛<br/>JACKPOT</div><div className={`window ${spinning?"rolling":""} ${wins.length?"celebrate":""}`}><div className="reels">{grid.map((reel,c)=><div className="reel" key={c}><div className="reelTrack">{(spinning?[...SPIN_STRIPS[c].slice(0,9),...spinTarget[c]]:reel).map((s,r)=><div className={`symbol ${s}`} key={`${c}-${r}`}><img src={DATA[s].src} alt={DATA[s].g}/></div>)}</div></div>)}</div><svg className="overlay" viewBox="0 0 500 300" preserveAspectRatio="none">{wins.map((i,n)=><polyline key={i} points={points[i]} style={{stroke:COLORS[n%COLORS.length]}}/>)}</svg></div><div className="lever"><i/><b/></div>{wins.length>0&&<div className="confetti">{Array.from({length:28},(_,i)=><i key={i} style={{left:`${(i*37)%100}%`,animationDelay:`${(i%9)*-.11}s`,background:COLORS[i%5]}}/>)}</div>}</section>
 <div className={`result ${wins.length?"won":""}`}>{spinning?"GOOD LUCK!":wins.length?`${wins.length} LINE${wins.length>1?"S":""} WIN  •  +${amount} COINS`:"20 ANIMATED PAYLINES"}</div>
 <section className="controls"><button onClick={()=>setBet(bet===50?10:bet+10)}>BET<br/>{bet}</button><button className={auto?"on":""} onClick={()=>setAuto(!auto)}>AUTO<br/>{auto?"ON":"OFF"}</button><button className="spin" disabled={spinning||coins<bet} onClick={spin}>SPIN</button><button onClick={()=>setPaytable(true)}>PAY<br/>TABLE</button><button onClick={fullscreen}>⛶<br/>FULL</button></section>
 <button className="lineToggle" onClick={()=>setCount(count===20?10:20)}>ACTIVE LINES <b>{count}</b> · TAP TO CHANGE</button>
 {paytable&&<div className="shade" onClick={()=>setPaytable(false)}><section className="paytable" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setPaytable(false)}>×</button><h2>20 PAYLINES</h2><p>Match 3 or more identical symbols from the leftmost reel.</p><div className="gallery">{LINES.map((_,i)=><div className="card" key={i}><span>{i+1}</span><svg viewBox="0 0 500 300" preserveAspectRatio="none"><polyline points={points[i]} style={{stroke:COLORS[i%5]}}/></svg></div>)}</div><div className="values">{KEYS.map(k=><span key={k}><img src={DATA[k].src} alt={DATA[k].g}/> × {DATA[k].p}</span>)}</div></section></div>}</main>
}
